HAL API to retrieve connected client information via Netlink and iw
rdkcentral/rdkb-turris-hal pull request #28
Opened 2019-11-25 07:34 UTC by Rajakumaran1106

Signed-off-by: Rajakumaran1106 <rajakumaran.a@ltts.com>

2019-11-25 09:11 UTC, manigandanj requested changes

2019-11-25 09:11 UTC, manigandanj commented on source/wifi/wifi_hal.c
> +    file = fopen("/tmp/wifi_signalstrength.txt", "r");
I would like have errror handling like this 
    file = fopen("", ...);
    if(file==NULL)
    {
        perror("fopen failed");
        return -1;
    }

2020-03-02 10:31 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkb-turris-hal?pullRequest=28) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkb-turris-hal?pullRequest=28) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkb-turris-hal?pullRequest=28) it.</sub>

2020-03-06 16:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkb-turris-hal?pullRequest=28) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkb-turris-hal?pullRequest=28) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkb-turris-hal?pullRequest=28) it.</sub>

2021-12-30 14:34 UTC, scthunderbolt commented
Abandoned due to inactivity, please restore if still needed.

2021-12-30 14:34 UTC, closed without merging