Hal API to retrieve TID stats via iw and Netlink, Adding Hal test binary
rdkcentral/rdkb-turris-hal pull request #37
Opened 2019-12-03 13:35 UTC by Rajakumaran1106

Signed-off-by: Rajakumaran1106 <rajakumaran.a@ltts.com>

2019-12-03 15:47 UTC, manigandanj requested changes

2019-12-03 15:47 UTC, manigandanj commented on source/wifi/Makefile.am
>  libhal_wifi_la_CPPFLAGS = -I$(top_srcdir)/./include $(CPPFLAGS)
remove this "./"

2019-12-03 15:47 UTC, manigandanj commented on source/wifi/Makefile.am
> +wifihal_CPPFLAGS = -I$(top_srcdir)/include $(CPPFLAGS)
Add -DWIFI_HAL_TEST in CPPFLAGS

2019-12-03 15:47 UTC, manigandanj commented on source/wifi/wifi_hal.c
> +#define WIFI_HAL_TEST
Must remove this line.

2019-12-03 15:47 UTC, manigandanj commented on source/wifi/wifi_hal.c
> +    char  if_name[10];
one space is enough

2019-12-04 09:25 UTC, manigandanj commented
Looks okay to me. It can be merged.

2019-12-04 10:50 UTC, rajkumar154 approved these changes

2019-12-04 10:51 UTC, merged