Fixed a couple of crash issues
rdkcentral/rdkb-turris-hal pull request #42
Opened 2019-12-19 10:07 UTC by yanhou-syna

Fixed a couple of crash issues while I'm trying to bringup CcspWifiSsp on Turris gateway build.

2019-12-19 10:56 UTC, manigandanj requested changes
Apart from one expected change, everything looks good to me.

2019-12-19 10:56 UTC, manigandanj commented on source/wifi/wifi_hal.c
> -        strcpy(params.name,"rsn_pairwise");
Its is valid change. We should have handled this as part of this commit 54833c023ddff2d8daefe6ce09041c6069c14a42 where we changed char name[64]-> char *name. 
Requesting you to make similar change in wifi_setApBasicAuthenticationMode API also.

2019-12-20 10:43 UTC, rajkumar154 approved these changes

2019-12-20 10:44 UTC, rajkumar154 approved these changes

2019-12-20 14:14 UTC, merged