Changes needed to enable WiFi dmcli
rdkcentral/rdkb-turris-hal pull request #43
Opened 2019-12-23 13:38 UTC by Rajakumaran1106

Signed-off-by: Rajakumaran1106 <rajakumaran.a@ltts.com>

2019-12-23 13:47 UTC, manigandanj requested changes

2019-12-23 13:47 UTC, manigandanj commented on source/wifi/wifi_hal.c
> +         char buf[32]= {'\0'};
In this block, there are 5 spaces instead of 4 spaces

2019-12-23 13:47 UTC, manigandanj commented on source/wifi/wifi_hal.c
> +        params.name = malloc(strlen("rsn_pairwise"));
free is not called for this allocation. can simple assign _rsn_pairwise_ to _params.name_

2019-12-24 07:22 UTC, rajkumar154 approved these changes

2019-12-24 07:22 UTC, merged